# Generated by Django 4.2.1 on 2023-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='hiooo', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
